#!/usr/bin/env python3
"""
Make a Chinese promotional poster for the comfyui skill.
- Loads a background image generated by Flux
- Upscales to 1024x1536 (poster aspect)
- Adds dark overlay for text readability
- Overlays title, subtitle, advantages, usage, footer using Noto Sans CJK
"""

import sys
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont, ImageFilter


def find_font(candidates):
    for path in candidates:
        if Path(path).exists():
            return path
    return None


def measure_text(draw, text, font):
    bbox = draw.textbbox((0, 0), text, font=font)
    return bbox[2] - bbox[0], bbox[3] - bbox[1]


def main():
    if len(sys.argv) < 3:
        print("Usage: make_poster.py <background.png> <output.png>", file=sys.stderr)
        sys.exit(1)

    bg_path = Path(sys.argv[1])
    out_path = Path(sys.argv[2])

    W, H = 1024, 1536

    font_bold = find_font(
        [
            "/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc",
            "/usr/share/fonts/opentype/noto/NotoSansCJK-Black.ttc",
            "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
        ]
    )
    font_reg = find_font(
        [
            "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
        ]
    )
    if not font_bold or not font_reg:
        print("错误: 找不到 Noto Sans CJK 字体", file=sys.stderr)
        sys.exit(1)

    img = Image.open(bg_path).convert("RGB")
    img = img.resize((W, H), Image.LANCZOS)

    overlay = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    odraw = ImageDraw.Draw(overlay)
    odraw.rectangle([(0, 0), (W, int(H * 0.45))], fill=(8, 10, 28, 170))
    odraw.rectangle([(0, int(H * 0.35)), (W, H)], fill=(8, 10, 28, 110))
    img = Image.alpha_composite(img.convert("RGBA"), overlay).convert("RGB")

    draw = ImageDraw.Draw(img)

    title_size = 76
    subtitle_size = 38
    section_size = 34
    body_size = 30
    small_size = 24
    code_size = 28

    title_font = ImageFont.truetype(font_bold, title_size)
    subtitle_font = ImageFont.truetype(font_reg, subtitle_size)
    section_font = ImageFont.truetype(font_bold, section_size)
    body_font = ImageFont.truetype(font_reg, body_size)
    small_font = ImageFont.truetype(font_reg, small_size)
    code_font = ImageFont.truetype(font_bold, code_size)

    cyan = (108, 244, 255)
    magenta = (255, 110, 220)
    white = (245, 248, 255)
    gray = (190, 200, 220)
    accent = (140, 200, 255)

    cx = W // 2

    y = 90
    badge = "  OPENCODE SKILL  "
    bw, bh = measure_text(draw, badge, small_font)
    bx0, by0 = cx - bw // 2 - 14, y - 8
    bx1, by1 = cx + bw // 2 + 14, y + bh + 8
    draw.rounded_rectangle(
        [bx0, by0, bx1, by1], radius=18, fill=(108, 244, 255, 255), outline=None
    )
    draw.text((cx - bw // 2, y - 4), badge, font=small_font, fill=(10, 20, 40))
    y += bh + 40

    title = "ComfyUI 自然语言控制技能"
    tw, th = measure_text(draw, title, title_font)
    draw.text((cx - tw // 2, y), title, font=title_font, fill=white)
    y += th + 18

    sub = "一句话生成图片 · 视频 · 工作流"
    sw, sh = measure_text(draw, sub, subtitle_font)
    draw.text((cx - sw // 2, y), sub, font=subtitle_font, fill=cyan)
    y += sh + 24

    div_w = 280
    draw.line([(cx - div_w // 2, y), (cx + div_w // 2, y)], fill=magenta, width=3)
    y += 40

    advantages = [
        ("⚡", "一句话生图", "txt2img / img2img 一次完成"),
        ("🌐", "远程服务器", "云端 GPU · 不占本地资源"),
        ("🎨", "多模型支持", "SD 1.5 / SDXL / Flux 全兼容"),
        ("🧩", "智能工作流", "模板 · 变量 · 一键调用"),
    ]
    grid_x0 = 80
    grid_x1 = W - 80
    cell_w = (grid_x1 - grid_x0) // 2
    cell_h = 130
    for idx, (icon, head, desc) in enumerate(advantages):
        col = idx % 2
        row = idx // 2
        x0 = grid_x0 + col * cell_w
        cy0 = y + row * cell_h
        x1 = x0 + cell_w - 20
        cy1 = cy0 + cell_h - 20
        draw.rounded_rectangle(
            [x0 + 10, cy0, x1, cy1], radius=16, outline=cyan, width=2
        )
        draw.text((x0 + 30, cy0 + 18), icon, font=title_font, fill=magenta)
        draw.text((x0 + 30, cy0 + 78), head, font=section_font, fill=white)
        draw.text((x0 + 30, cy0 + 118), desc, font=small_font, fill=gray)
    y += cell_h * 2 + 20

    usage_title = "快速上手"
    draw.text((grid_x0 + 10, y), usage_title, font=section_font, fill=cyan)
    y += section_size + 18

    cmds = [
        ("/comfyui init", "初始化配置"),
        ("/comfyui txt2img 描述", "文生图"),
        ("/comfyui img2img 描述", "图生图"),
        ("/comfyui status", "查看状态"),
    ]
    for cmd, desc in cmds:
        cw, ch = measure_text(draw, cmd, code_font)
        draw.rounded_rectangle(
            [grid_x0 + 10, y, grid_x0 + 30 + cw + 20, y + ch + 12],
            radius=8,
            fill=(20, 28, 56),
        )
        draw.text((grid_x0 + 30, y + 6), cmd, font=code_font, fill=accent)
        draw.text((grid_x0 + 50 + cw + 30, y + 4), desc, font=body_font, fill=gray)
        y += max(ch + 16, 48)

    y += 30
    footer = "开源 · 远程 ComfyUI 控制 · 自然语言驱动"
    fw, fh = measure_text(draw, footer, small_font)
    draw.text((cx - fw // 2, y), footer, font=small_font, fill=gray)
    y += fh + 12
    brand = "comfyui  ·  /comfyui  ·  powered by Flux + Pillow"
    bw2, _ = measure_text(draw, brand, small_font)
    draw.text((cx - bw2 // 2, y), brand, font=small_font, fill=(120, 140, 170))

    img.save(out_path, "PNG", optimize=True)
    print(f"OK: {out_path} ({out_path.stat().st_size // 1024} KB, {img.size})")


if __name__ == "__main__":
    main()
